/*
 * ads1256.c
 *
 * Minimal polled ADS1256 driver for the 6 pack thermistors. We mux through
 * AIN0..AIN5 single-ended (vs AINCOM) one channel per cycle, waiting on the
 * DRDY line between channels. No RDATAC, no DMA — at 10 Hz the simple
 * stop-data-continuous + RDATA-per-sample flow is plenty and easy to reason
 * about on a scope.
 *
 * Register/command values and timing follow the ADS1256 datasheet (SBAS288).
 */

#include "ads1256.h"

/* ---- Pin mapping -----------------------------------------------------------
 * CS is generated by CubeMX (PA8, label "CS"). DRDY (PD8) may not be in the
 * .ioc yet, so we both provide fallback macros AND configure the pin in
 * ads1256_init() — harmless if CubeMX also inits it. */
#ifndef DRDY_Pin
#define DRDY_Pin        GPIO_PIN_8
#define DRDY_GPIO_Port  GPIOD
#endif

#define CS_LOW()    HAL_GPIO_WritePin(CS_GPIO_Port,  CS_Pin,  GPIO_PIN_RESET)
#define CS_HIGH()   HAL_GPIO_WritePin(CS_GPIO_Port,  CS_Pin,  GPIO_PIN_SET)
#define DRDY_IS_LOW() (HAL_GPIO_ReadPin(DRDY_GPIO_Port, DRDY_Pin) == GPIO_PIN_RESET)

/* ---- ADS1256 commands ---------------------------------------------------- */
#define ADS_CMD_WAKEUP   0x00u
#define ADS_CMD_RDATA    0x01u
#define ADS_CMD_SDATAC   0x0Fu
#define ADS_CMD_RREG     0x10u   /* | reg  (then count-1) */
#define ADS_CMD_WREG     0x50u   /* | reg  (then count-1) */
#define ADS_CMD_SELFCAL  0xF0u
#define ADS_CMD_SYNC     0xFCu
#define ADS_CMD_RESET    0xFEu

/* ---- Registers ----------------------------------------------------------- */
#define ADS_REG_STATUS   0x00u
#define ADS_REG_MUX      0x01u
#define ADS_REG_ADCON    0x02u
#define ADS_REG_DRATE    0x03u

/* STATUS: MSB-first (ORDER=0), auto-cal on (ACAL=1), input buffer on (BUFEN=1).
 * The buffer helps with the relatively high-impedance thermistor dividers. */
#define ADS_STATUS_CFG   0x06u
/* ADCON: clock-out off, sensor-detect off, PGA gain = 1 (raw curve owns scale). */
#define ADS_ADCON_CFG    0x00u
/* DRATE: 1000 SPS — fast enough that muxing 6 channels per 100 ms tick has
 * ample settling margin; the thermistor signal itself is slow so the extra
 * bandwidth/noise is irrelevant at 1 C/LSB. Tune if you want quieter codes. */
#define ADS_DRATE_CFG    0xA1u

/* AINCOM is mux code 0x08; single-ended channel i = (i<<4) | AINCOM. */
#define ADS_MUX_SE(ch)   (uint8_t)(((ch) << 4) | 0x08u)

/* DRDY poll budget: a 1000 SPS conversion is ~1 ms; after a mux change the
 * part needs a few conversions to settle. Loop count is generous and only a
 * timeout backstop, not the normal exit path. */
#define DRDY_TIMEOUT_LOOPS   200000u
#define SPI_TIMEOUT_MS       10u

/* Rough microsecond busy-wait for the few short datasheet delays (t6, t11).
 * Core is 168 MHz; ~one iteration is a handful of cycles, so this overshoots
 * slightly — fine, these are minimum-delay constraints. */
static void ads_delay_us(uint32_t us)
{
    volatile uint32_t n = us * 40u;
    while (n--) { __asm volatile("nop"); }
}

static uint8_t ads_xfer(uint8_t tx)
{
    uint8_t rx = 0;
    (void)HAL_SPI_TransmitReceive(&hspi1, &tx, &rx, 1, SPI_TIMEOUT_MS);
    return rx;
}

static void ads_cmd(uint8_t cmd)
{
    (void)ads_xfer(cmd);
}

static void ads_wreg(uint8_t reg, uint8_t val)
{
    (void)ads_xfer((uint8_t)(ADS_CMD_WREG | reg));
    (void)ads_xfer(0x00);   /* write 1 register (count - 1 = 0) */
    (void)ads_xfer(val);
}

/* Wait for DRDY to go low. Returns 1 if ready, 0 on timeout. */
static uint8_t ads_wait_drdy(void)
{
    uint32_t guard = DRDY_TIMEOUT_LOOPS;
    while (guard--) {
        if (DRDY_IS_LOW()) {
            return 1u;
        }
    }
    return 0u;
}

void ads1256_init(void)
{
    /* Ensure DRDY (PD8) is a usable input even if it isn't in the .ioc. */
    __HAL_RCC_GPIOD_CLK_ENABLE();
    GPIO_InitTypeDef in = {0};
    in.Pin  = DRDY_Pin;
    in.Mode = GPIO_MODE_INPUT;
    in.Pull = GPIO_NOPULL;   /* ADS1256 drives DRDY push-pull */
    HAL_GPIO_Init(DRDY_GPIO_Port, &in);

    CS_HIGH();
    HAL_Delay(5);            /* let supplies/oscillator settle */

    CS_LOW();
    ads_cmd(ADS_CMD_RESET);
    HAL_Delay(5);            /* datasheet: ready ~0.6 ms after reset; be safe */
    ads_cmd(ADS_CMD_SDATAC); /* stop read-data-continuous before WREG access */

    ads_wreg(ADS_REG_STATUS, ADS_STATUS_CFG);
    ads_wreg(ADS_REG_ADCON,  ADS_ADCON_CFG);
    ads_wreg(ADS_REG_DRATE,  ADS_DRATE_CFG);
    ads_wreg(ADS_REG_MUX,    ADS_MUX_SE(0));

    ads_cmd(ADS_CMD_SELFCAL);
    (void)ads_wait_drdy();   /* calibration done when DRDY falls */
    CS_HIGH();
}

void ads1256_read_all(uint16_t *raw, uint8_t *valid)
{
    CS_LOW();

    for (uint8_t ch = 0; ch < ADS1256_THERM_COUNT; ch++) {
        raw[ch]   = 0;
        valid[ch] = 0;

        /* Point the mux at the next channel and restart conversion. */
        ads_wreg(ADS_REG_MUX, ADS_MUX_SE(ch));
        ads_cmd(ADS_CMD_SYNC);
        ads_cmd(ADS_CMD_WAKEUP);

        /* Wait for the freshly-settled conversion on this channel. */
        if (!ads_wait_drdy()) {
            continue;        /* leave raw=0, valid=0 on timeout */
        }

        ads_cmd(ADS_CMD_RDATA);
        ads_delay_us(7);     /* t6: >= 50 tCLKIN (~6.5 us) before DOUT is valid */

        uint8_t b2 = ads_xfer(0xFF);   /* MSB */
        uint8_t b1 = ads_xfer(0xFF);
        uint8_t b0 = ads_xfer(0xFF);   /* LSB */

        /* Assemble the 24-bit two's-complement code, sign-extend to 32 bits. */
        int32_t code = ((int32_t)b2 << 16) | ((int32_t)b1 << 8) | (int32_t)b0;
        if (code & 0x00800000) {
            code |= (int32_t)0xFF000000;
        }

        /* The downstream interface (thermistor_raw_to_c) is a uint16_t raw with
         * an UNCALIBRATED placeholder curve. Single-ended thermistor dividers
         * read positive, so clamp any negative code to 0 and pass the upper 16
         * bits (drop the low 8). When the real calibration lands it should work
         * off the full 24-bit code / known Vref instead — flag for that owner. */
        if (code < 0) {
            code = 0;
        }
        raw[ch]   = (uint16_t)((uint32_t)code >> 8);
        valid[ch] = 1;
    }

    CS_HIGH();
}
